# Site settings
title: ZhengZhang's Blog                     #博客标题
SEOTitle: ZhengZhang's Blog         #显示在浏览器上搜索的时候显示的标题
# header-img: img/post-bg-rwd.jpg      #显示在首页的背景图片
email: sendtozhangzheng@gmail.com    
description: "You are what you write"               #网站介绍
# keyword: "BY, BY Blog, 柏荧的博客, qiubaiying, 邱柏荧, iOS, Apple, iPhone" #关键词
url: "https://kiwibird01.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写

theme: jekyll-theme-midnight